export default {
    LOGIN_CURR_USER: 'LOGIN_CURR_USER',
    LOGOUT_CURR_USER: 'LOGOUT_CURR_USER',
    UPDATE_CURR_USER: 'UPDATE_CURR_USER',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    GET_USERS: 'GET_USERS',
    FOLLOW_USERS: 'FOLLOW_USERS',
    GET_USER_BYID: 'GET_USER_BYID',
    CREATE_POST: 'CREATE_POST',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    GET_FEED: 'GET_FEED',
    LIKE_POST: 'LIKE_POST',
    GET_POST_BY_ID: 'GET_POST_BY_ID',
    GET_USERS_BY_LOGIN: 'GET_USERS_BY_LOGIN'
}